

"use client";

import React, { useEffect, useRef, useState } from "react";
import { db } from "../lib/firebase";
import { collection, getDocs } from "firebase/firestore";

interface RequestData {
  id: string;
  "Customer-Name": string;
  "User-Email": string;
  "Phone-Number": string;
  Address: string;
  Courier: string;
  "Product-Name": string[] | string;
  Quantity: string;
  Time: { seconds: number };
}

const RequestTable = () => {
  const [requests, setRequests] = useState<RequestData[]>([]);
  const [selectedRequest, setSelectedRequest] = useState<RequestData | null>(null);
  const printRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const fetchRequests = async () => {
      const querySnapshot = await getDocs(collection(db, "user_request"));
      const requestsData: RequestData[] = [];
      querySnapshot.forEach((doc) => {
        requestsData.push({ id: doc.id, ...doc.data() } as RequestData);
      });
      setRequests(requestsData);
    };

    fetchRequests();
  }, []);

  const handlePrintInvoice = (request: RequestData) => {
    setSelectedRequest(request);
    setTimeout(() => {
      window.print();
    }, 100); // Give the DOM time to render the invoice
  };

  return (
    <div className="w-full">
      <h2 className="text-2xl font-bold text-gray-800 mb-6">User Requests</h2>

      {/* Printable Invoice Section */}
      {selectedRequest && (
        <div className="hidden print:block p-8" ref={printRef}>
          <h1 className="text-2xl font-bold mb-4">Invoice</h1>
          <p><strong>Customer:</strong> {selectedRequest["Customer-Name"]}</p>
          <p><strong>Email:</strong> {selectedRequest["User-Email"]}</p>
          <p><strong>Phone:</strong> {selectedRequest["Phone-Number"]}</p>
          <p><strong>Address:</strong> {selectedRequest["Address"]}</p>
          <p><strong>Courier:</strong> {selectedRequest["Courier"]}</p>
          <p><strong>Product:</strong> {
            Array.isArray(selectedRequest["Product-Name"])
              ? selectedRequest["Product-Name"].join(", ")
              : selectedRequest["Product-Name"]
          }</p>
          <p><strong>Quantity:</strong> {selectedRequest["Quantity"]}</p>
          <p><strong>Time:</strong> {new Date(selectedRequest["Time"].seconds * 1000).toLocaleString()}</p>
          <p className="mt-6 text-sm text-gray-500">Generated by Web App</p>
        </div>
      )}

      {/* Request Table */}
      <div className="overflow-x-auto bg-white shadow-lg rounded-2xl border border-gray-200">
        <table className="w-full text-sm text-gray-800 divide-y divide-gray-200">
          <thead className="bg-blue-500 text-white">
            <tr>
              <th className="px-3 py-2 text-left font-medium">Customer</th>
              <th className="px-3 py-2 text-left font-medium">Email</th>
              <th className="px-3 py-2 text-left font-medium">Phone</th>
              <th className="px-3 py-2 text-left font-medium">Address</th>
              <th className="px-3 py-2 text-left font-medium">Courier</th>
              <th className="px-3 py-2 text-left font-medium">Product</th>
              <th className="px-3 py-2 text-left font-medium">Quantity</th>
              <th className="px-3 py-2 text-left font-medium">Time</th>
              <th className="px-3 py-2 text-left font-medium">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100">
            {requests.length > 0 ? (
              requests.map((request) => (
                <tr key={request.id} className="hover:bg-gray-50 transition">
                  <td className="px-3 py-2">{request["Customer-Name"]}</td>
                  <td className="px-3 py-2">{request["User-Email"]}</td>
                  <td className="px-3 py-2">{request["Phone-Number"]}</td>
                  <td className="px-3 py-2">{request["Address"]}</td>
                  <td className="px-3 py-2">{request["Courier"]}</td>
                  <td className="px-3 py-2">
                    {Array.isArray(request["Product-Name"])
                      ? request["Product-Name"].join(", ")
                      : request["Product-Name"]}
                  </td>
                  <td className="px-3 py-2">{request["Quantity"]}</td>
                  <td className="px-3 py-2">
                    {new Date(request["Time"].seconds * 1000).toLocaleString()}
                  </td>
                  <td className="px-3 py-2">
                    <button
                      onClick={() => handlePrintInvoice(request)}
                      className="text-blue-600 hover:underline"
                    >
                      Create Invoice
                    </button>
                  </td>
                </tr>
              ))
            ) : (
              <tr>
                <td colSpan={9} className="px-4 py-4 text-center text-gray-400">
                  No data available
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default RequestTable;
